# Generated by Django 4.2.1 on 2023-06-23 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nama_cabang', models.CharField(max_length=100, unique=True)),
                ('deskripsi', models.TextField()),
                ('sejarah', models.TextField()),
            ],
        ),
    ]
